from extended_permissions.backends import ExtendedModelBackend
from shib_auth.backends import ShibbolethBackend

class BikeshareDummyBackend(ExtendedModelBackend): pass
class BikeshareShibBackend(ExtendedModelBackend, ShibbolethBackend): pass